#! /bin/bash

# English forced in URL
/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Commands/java -d32 -Dpython.path=Lib/ -jar /Applications/Sikuli-IDE.app/Contents/Resources/Java/sikuli-ide.jar -r /Volumes/www/magictree/ZTesting/osx/safari/moe/display/search_modify.sikuli --args "http://tree.dtravel/demo/" "http://pma.dtravel/" "ENG" "50"> /Volumes/www/magictree/ZTesting/osx/safari/moe/display/search_modify_ENG.log

# French forced in URL
#/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Commands/java -d32 -Dpython.path=Lib/ -jar /Applications/Sikuli-IDE.app/Contents/Resources/Java/sikuli-ide.jar -r /Volumes/www/magictree/ZTesting/osx/safari/moe/display/search_modify.sikuli --args "http://tree.dtravel/demo/" "http://pma.dtravel/" "FRA" "10"> /Volumes/www/magictree/ZTesting/osx/safari/moe/display/search_modify_FRA.log

# Default system language
#/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Commands/java -d32 -Dpython.path=Lib/ -jar /Applications/Sikuli-IDE.app/Contents/Resources/Java/sikuli-ide.jar -r /Volumes/www/magictree/ZTesting/osx/safari/moe/display/search_modify.sikuli --args "http://tree.dtravel/demo/" "http://pma.dtravel/" "" "3"> /Volumes/www/magictree/ZTesting/osx/safari/moe/display/search_modify_DEFAULT.log

echo "###this is the end phrase###"